name: Generate Solar System Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python 3.10
      run: |
        sudo apt update
        sudo apt install python3.10
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        pip install matplotlib numpy

    - name: Run animation script
      run: |
        python animation_script.py  # Replace 'animation_script.py' with the name of your Python script

    - name: Upload animation artifact
      uses: actions/upload-artifact@v2
      with:
        name: solar_sys_animation
        path: solar_sys.gif

