name: Generate Solar System Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Working Directory
        run: pwd

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Print Working Directory
        run: pwd

      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Working Directory
        run: pwd  

      - name: Run animation script
        run: python workspace.py

      - name: Print Working Directory
        run: pwd  

      - name: Upload animation artifact
        uses: actions/upload-artifact@v2
        with:
          name: solar_sys_animation
          path: solar_sys.gif